### ISSUE TITLE
Issue with scraping 

### ISSUE THREAD

**Issue by glitchdog69** [debadridtt/Scraping-Google-Images-using-Python#1]
Getting stuck on loop. Any one else having this issue? Some times it will download - 1 - 2 images fine then on the next search term glitch out?

Starting search for Images
Found: 212 search results. Extracting links from 100:212
Starting search for Images
Found: 261 search results. Extracting links from 212:261
Starting search for Images
Found: 261 search results. Extracting links from 261:261
Starting search for Images
Found: 261 search results. Extracting links from 261:261
Starting search for Images
Found: 261 search results. Extracting links from 261:261
Starting search for Images
Found: 261 search results. Extracting links from 261:261
Starting search for Images
Found: 261 search results. Extracting links from 261:261
Starting search for Images
Found: 261 search results. Extracting links from 261:261
Starting search for Images
Found: 261 search results. Extracting links from 261:261
Starting search for Images
Found: 261 search results. Extracting links from 261:261
Starting search for Images
Found: 261 search results. Extracting links from 261:261
Starting search for Images
Found: 261 search results. Extracting links from 261:261
Starting search for Images
Found: 261 search results. Extracting links from 261:261
Starting search for Images

**Comment by debadridtt** [comment]
Have updated the notes, the script seems to run completely and smoothly if the range lies between 200-250. You can modify your search input query a bit and do it in 3/4 batches if you are looking for around 800-1000 images
