### ISSUE TITLE
Chrome Permission denied

### ISSUE THREAD

**Issue by ravipandey95** [debadridtt/Scraping-Google-Images-using-Python#4]
I am trying to implement this module in Google colab and I am getting this error.
<img width="875" alt="error" src="https://user-images.githubusercontent.com/80535789/196107986-38b58c65-3dbe-4620-b07d-159069fdf5fe.png">

**Comment by debadridtt** [comment]
This code needs to be run on local system. There is no need of GPU or anything, simple Anaconda installation with Python 3.6+ should be good enough

The script is not executable from AWS/Azure/Kaggle/Google collab, etc.
